# Copyright Altran Netherlands B.V

project: xtext-move-refactoring
language: Java
default_branch: "develop"
code_location:
  source:
    - ./plugins/
    - ./releng/
  test:
    - ./tests/
artifact_repository_url: "https://nexus.acidspace.nl/repository/{}/{}{}"

build:
  binaries:
    platform: Maven
    precondition:
      - OutputDirectoryExists
      - OutputDirectoryIsEmpty
    postcondition:
      - OutputDirectoryIsNotEmpty
    parameters:
      output: ./reports/build/binaries
      build_settings_path: ./settings.xml
      build_pom_path: ./pom.xml

test:
  units:
    platform: Maven
    precondition:
      - OutputDirectoryExists
      - OutputDirectoryIsEmpty
    postcondition:
      - OutputDirectoryIsNotEmpty
    parameters:
      output: ./reports/test/units
      test_settings_path: ./settings.xml
      test_pom_path: ./pom.xml
      index: test-units
    gate:
      - metric: NumberOfTests
        threshold: 0
        operator: "="

release:
  binaries:
    platform: P2
    precondition:
      - OutputDirectoryExists
      - OutputDirectoryIsEmpty
    postcondition:
      - OutputDirectoryIsNotEmpty
    parameters:
      repository: mde_assets-xtext_move_refactoring-raw
      repository_project: ./releng/com.altran.general.xtext.refactoring.move.repository
      output: ./reports/release/binaries
